#!/usr/bin/env bash
# The desktop-wide switch: floating desktop (everything floats, the default
# here) or plain tiling i3. $mod+Shift+space still flips one window in either.
#
#   desktop_mode.sh            → toggle
#   desktop_mode.sh floating   → floating desktop
#   desktop_mode.sh tiling     → tiling desktop
#   desktop_mode.sh status     → print the mode, change nothing
#
# Tiling mode is a generated .local file the config already includes, plus a
# reload: rules, not a daemon, so a window is never mapped floating and then
# yanked into the layout a frame later. Its presence *is* the stored mode.
set -eu

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Last of the `include ~/.i3rc/*.local` files by name, so its rules run after
# the catch-all in config that floats everything — order is what undoes it.
MODE_FILE=${I3RC_MODE_FILE:-$HOME/.i3rc/90-tiling-mode.local}

# Classes that stay floating in tiling mode: their window *is* the screen.
# Same default as float.sh's skip list, and the rules below repeat it.
KEEP_CLASS_RE=${I3RC_FLOAT_SKIP:-'^(flameshot|i3lock)$'}

JQ_DESC='def desc: recurse(.nodes[]?, .floating_nodes[]?);'

current_mode() {
    [ -e "$MODE_FILE" ] && printf 'tiling\n' || printf 'floating\n'
}

write_mode_file() {
    cat > "$MODE_FILE" <<'EOF'
# Generated by ~/.i3rc/scripts/desktop_mode.sh — tiling mode. Delete it and
# reload i3 for the floating desktop; the script does exactly that.

# Runs after config's `for_window [class=".*"] floating enable`: i3 applies
# both at manage time, so the window is tiled before it is ever drawn.
for_window [window_type="normal"] floating disable

# Put back the three the rule above must not touch. A scratchpad window tiled
# into __i3_scratch is a window you can no longer show.
for_window [workspace="^__i3"] floating enable
for_window [class="(?i)^flameshot$"] floating enable
for_window [class="(?i)firefox" title="^Picture-in-Picture$"] floating enable, sticky enable
EOF
}

# con ids of the windows a switch has to move, jq filter $1 picking the
# direction. Never the scratchpad, the sticky ones or the keep-classes.
targets() {
    i3-msg -t get_tree | jq -r --arg keep "$KEEP_CLASS_RE" "$JQ_DESC"'
        desc | select(.type == "workspace")
             | select(.name | startswith("__i3") | not)
             | desc | select(.window != null)
             | select(.window_type == "normal")
             | select(.sticky != true)
             | select((.window_properties.class // "") | test($keep) | not)
             | select('"$1"')
             | .id'
}

# One i3-msg for the whole sweep: a separate call per window is a fork each,
# and i3 runs a comma-free `;` list in order anyway.
run_each() {
    local cmd=$1 id out=""
    shift
    for id in "$@"; do out+="[con_id=$id] $cmd; "; done
    [ -n "$out" ] || return 0
    i3-msg "${out%; }" >/dev/null
}

to_tiling() {
    local ids=()
    write_mode_file
    i3-msg reload >/dev/null
    mapfile -t ids < <(targets '.floating == "user_on" or .floating == "auto_on"')
    run_each 'floating disable' "${ids[@]}"
}

to_floating() {
    local ids=() id
    rm -f "$MODE_FILE"
    i3-msg reload >/dev/null
    mapfile -t ids < <(targets '.floating == "user_off" or .floating == "auto_off"')
    run_each 'floating enable' "${ids[@]}"
    # Floating alone leaves them at whatever size the layout gave them: place
    # each one the way float.sh would have, had it opened floating.
    for id in "${ids[@]}"; do "$HERE/float.sh" place "$id"; done
}

notify() {
    command -v notify-send >/dev/null 2>&1 || return 0
    notify-send -a "desktop" -r 90914 -t 1500 "Desktop" "$1"
}

mode=${1:-toggle}
if [ "$mode" = "toggle" ]; then
    [ "$(current_mode)" = "tiling" ] && mode=floating || mode=tiling
fi

case "$mode" in
    floating) to_floating; notify "Floating desktop" ;;
    tiling)   to_tiling;   notify "Tiling desktop" ;;
    status)   current_mode ;;
    *) printf 'usage: %s [toggle|floating|tiling|status]\n' "${0##*/}" >&2; exit 2 ;;
esac
