#!/usr/bin/env bash
# The desktop-wide switch: floating desktop (everything floats, the default
# here) or plain tiling i3. $mod+Shift+space still flips one window in either.
#
#   desktop_mode.sh            → toggle
#   desktop_mode.sh floating   → floating desktop
#   desktop_mode.sh tiling     → tiling desktop
#   desktop_mode.sh status     → print the mode, change nothing
#
# Tiling mode is two generated .local files the config already includes, plus a
# reload: rules, not a daemon, so a window is never mapped floating and then
# yanked into the layout a frame later. The 90- one's presence *is* the mode.
set -eu

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Last of the `include ~/.i3rc/*.local` files by name, so its rules run after
# the catch-all in config that floats everything — order is what undoes it.
MODE_FILE=${I3RC_MODE_FILE:-$HOME/.i3rc/90-tiling-mode.local}

# Sorts before every per-app border file (07-, 08-, config.local), so their
# `border pixel 1` still beats the thinner tiling border written here.
BORDER_FILE=${I3RC_BORDER_FILE:-$HOME/.i3rc/00-tiling-border.local}

# Left/right/bottom of a tiled window, px. Thinner than config's floating 3:
# tiled, two borders meet at every seam, so 2 still leaves a 4px drag handle.
TILE_BORDER_PX=${I3RC_TILE_BORDER_PX:-2}
FLOAT_BORDER_PX=3   # config's `border normal 3`, the width the switch swaps

# Classes that stay floating in tiling mode: their window *is* the screen.
# Same default as float.sh's skip list, and the rules below repeat it.
KEEP_CLASS_RE=${I3RC_FLOAT_SKIP:-'^(flameshot|i3lock)$'}

JQ_DESC='def desc: recurse(.nodes[]?, .floating_nodes[]?);'

current_mode() {
    [ -e "$MODE_FILE" ] && printf 'tiling\n' || printf 'floating\n'
}

write_border_file() {
    cat > "$BORDER_FILE" <<EOF
# Generated by ~/.i3rc/scripts/desktop_mode.sh — tiling mode, together with
# 90-tiling-mode.local. Sides only: the title bar is as tall as the font.

# Runs after config's \`border normal 3\` and before 07-/08-/config.local, so a
# per-app border set there still wins, exactly as it does over config.
for_window [window_type="normal"] border normal $TILE_BORDER_PX
EOF
}

write_mode_file() {
    cat > "$MODE_FILE" <<'EOF'
# Generated by ~/.i3rc/scripts/desktop_mode.sh — tiling mode, together with
# 00-tiling-border.local. `desktop_mode.sh floating` deletes both and reloads.

# Runs after config's `for_window [class=".*"] floating enable`: i3 applies
# both at manage time, so the window is tiled before it is ever drawn.
for_window [window_type="normal"] floating disable

# Put back the three the rule above must not touch. A scratchpad window tiled
# into __i3_scratch is a window you can no longer show.
for_window [workspace="^__i3"] floating enable
for_window [class="(?i)^flameshot$"] floating enable
for_window [class="(?i)firefox" title="^Picture-in-Picture$"] floating enable, sticky enable

# Tiled, only the focused window is coloured: config's own greys, put back over
# the 06-colors.local best-linux-environment writes. Last `client.*` line wins.
client.focused_inactive #3c3836 #3c3836 #a89984 #504945 #3c3836
client.unfocused        #282828 #282828 #a89984 #504945 #282828
EOF
}

# con ids of the windows a switch has to move, jq filter $1 picking the
# direction. Never the scratchpad, the sticky ones or the keep-classes.
targets() {
    i3-msg -t get_tree | jq -r --arg keep "$KEEP_CLASS_RE" "$JQ_DESC"'
        desc | select(.type == "workspace")
             | select(.name | startswith("__i3") | not)
             | desc | select(.window != null)
             | select(.window_type == "normal")
             | select(.sticky != true)
             | select((.window_properties.class // "") | test($keep) | not)
             | select('"$1"')
             | .id'
}

# One i3-msg for the whole sweep: a separate call per window is a fork each,
# and i3 runs a comma-free `;` list in order anyway.
run_each() {
    local cmd=$1 id out=""
    shift
    for id in "$@"; do out+="[con_id=$id] $cmd; "; done
    [ -n "$out" ] || return 0
    i3-msg "${out%; }" >/dev/null
}

to_tiling() {
    local ids=()
    write_border_file
    write_mode_file
    i3-msg reload >/dev/null
    mapfile -t ids < <(targets '.floating == "user_on" or .floating == "auto_on"')
    run_each 'floating disable' "${ids[@]}"
    # Rules only fire on new windows: swap the open ones' border here, and only
    # the catch-all's — a per-app `pixel 1` is not the switch's to touch.
    mapfile -t ids < <(targets ".border == \"normal\" and .current_border_width == $FLOAT_BORDER_PX")
    run_each "border normal $TILE_BORDER_PX" "${ids[@]}"
}

to_floating() {
    local ids=() id
    rm -f "$MODE_FILE" "$BORDER_FILE"
    i3-msg reload >/dev/null
    # Border back first: the style change resizes the frame, place.sh fixes it.
    mapfile -t ids < <(targets ".border == \"normal\" and .current_border_width == $TILE_BORDER_PX")
    run_each "border normal $FLOAT_BORDER_PX" "${ids[@]}"
    mapfile -t ids < <(targets '.floating == "user_off" or .floating == "auto_off"')
    run_each 'floating enable' "${ids[@]}"
    # Floating alone leaves them at whatever size the layout gave them: place
    # each one the way float.sh would have, had it opened floating.
    for id in "${ids[@]}"; do "$HERE/float.sh" place "$id"; done
}

notify() {
    command -v notify-send >/dev/null 2>&1 || return 0
    notify-send -a "desktop" -r 90914 -t 1500 "Desktop" "$1"
}

mode=${1:-toggle}
if [ "$mode" = "toggle" ]; then
    [ "$(current_mode)" = "tiling" ] && mode=floating || mode=tiling
fi

case "$mode" in
    floating) to_floating; notify "Floating desktop" ;;
    tiling)   to_tiling;   notify "Tiling desktop" ;;
    status)   current_mode ;;
    *) printf 'usage: %s [toggle|floating|tiling|status]\n' "${0##*/}" >&2; exit 2 ;;
esac
