#!/usr/bin/env bash
# Toggle the Alacritty terminal between dark and light colour schemes.
#
#   theme.sh            → toggle (dark <-> light)
#   theme.sh dark       → force dark  (Gruvbox Material Dark)
#   theme.sh light      → force light (Gruvbox Material Light)
#
# Colours only reach the terminal if Alacritty's config imports the theme file
# (INSTALL.md §9) — checked below, since writing it always "succeeds".
set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/theme_lib.sh" || exit 1

THEME_FILE="$ALACRITTY_THEME_FILE"
STATE_FILE="$HOME/.cache/theme-mode"
mkdir -p "$HOME/.cache"

mode="${1:-toggle}"
if [[ "$mode" == "toggle" ]]; then
    [[ "$(cat "$STATE_FILE" 2>/dev/null)" == "light" ]] && mode="dark" || mode="light"
fi

case "$mode" in
  dark)
    # Gruvbox Material Dark — the terminal's normal look, not a variant: the
    # Alacritty config defines no colours of its own and imports this file.
    cat > "$THEME_FILE" <<'EOF'
# Gruvbox Material Dark — generated by ~/.i3rc/scripts/theme.sh
[window]
opacity = 1

[colors.primary]
background = '0x1d2021'
foreground = '0xd4be98'

[colors.normal]
black   = '0x32302f'
red     = '0xea6962'
green   = '0xa9b665'
yellow  = '0xd8a657'
blue    = '0x7daea3'
magenta = '0xd3869b'
cyan    = '0x89b482'
white   = '0xd4be98'

[colors.bright]
black   = '0x998c7e'
red     = '0xf2837c'
green   = '0xbfcb7f'
yellow  = '0xe9bd75'
blue    = '0x9ac4ba'
magenta = '0xdfa0b1'
cyan    = '0xa3c99d'
white   = '0xebdbb2'

[colors.cursor]
# Same gruvbox yellow as tmux's pane-active-border-style, so "where the focus
# is" reads the same whether tmux or the terminal draws it.
cursor = '0xd79921'
EOF
    ;;
  light)
    # Gruvbox Material Light (Medium) — readable dark text on a light background.
    cat > "$THEME_FILE" <<'EOF'
# Gruvbox Material Light — generated by ~/.i3rc/scripts/theme.sh
[window]
opacity = 0.97

[colors.primary]
background = '0xfbf1c7'
foreground = '0x654735'

[colors.normal]
black   = '0x654735'
red     = '0xc14a4a'
green   = '0x6c782e'
yellow  = '0xb47109'
blue    = '0x45707a'
magenta = '0x945e80'
cyan    = '0x4c7a5d'
white   = '0xa89984'

[colors.bright]
black   = '0xa89984'
red     = '0xc14a4a'
green   = '0x6c782e'
yellow  = '0xb47109'
blue    = '0x45707a'
magenta = '0x945e80'
cyan    = '0x4c7a5d'
white   = '0x654735'

[colors.cursor]
cursor = '0xc35e0a'
EOF
    ;;
  *)
    echo "usage: theme.sh [toggle|dark|light]" >&2
    exit 1
    ;;
esac

echo "$mode" > "$STATE_FILE"

# Report what actually happened, not just that the file was written.
notify() {
    command -v notify-send >/dev/null 2>&1 || return 0
    notify-send -a "theme" -r 90913 -t "$1" "$2" "$3"
}

alacritty_cfg="$(alacritty_config)" || alacritty_cfg=""

if [[ -z "$alacritty_cfg" ]]; then
    notify 4000 "Terminal theme" "Wrote ${mode} theme, but no Alacritty config found to import it — see INSTALL.md §9."
elif ! alacritty_imports_theme "$alacritty_cfg"; then
    notify 6000 "Terminal theme" "Wrote ${mode} theme, but ${alacritty_cfg/#$HOME/\~} does not import it — see INSTALL.md §9."
else
    notify 1500 "Terminal theme" "Switched to ${mode} mode"
fi
